// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/admin/categories" | "/admin/categories/[id]" | "/admin/courses" | "/admin/courses/[id]" | "/admin/lessons" | "/admin/lessons/[id]" | "/admin/modules" | "/admin/modules/[id]" | "/courses/[slug]" | "/dashboard" | "/dashboard/courses" | "/lessons/[courseSlug]/[lessonSlug]" | "/notes" | "/pricing" | "/studio/[[...tool]]" | "/test-api"
type AppRouteHandlerRoutes = "/api/chat"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/admin/categories": {}
  "/admin/categories/[id]": { "id": string; }
  "/admin/courses": {}
  "/admin/courses/[id]": { "id": string; }
  "/admin/lessons": {}
  "/admin/lessons/[id]": { "id": string; }
  "/admin/modules": {}
  "/admin/modules/[id]": { "id": string; }
  "/api/chat": {}
  "/courses/[slug]": { "slug": string; }
  "/dashboard": {}
  "/dashboard/courses": {}
  "/lessons/[courseSlug]/[lessonSlug]": { "courseSlug": string; "lessonSlug": string; }
  "/notes": {}
  "/pricing": {}
  "/studio/[[...tool]]": { "tool"?: string[]; }
  "/test-api": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
