"use client";

import { defineConfig } from "sanity";
import { structureTool } from "sanity/structure";
import { visionTool } from "@sanity/vision";
import { muxInput } from "sanity-plugin-mux-input";

import { schema } from "./sanity/schemaTypes";
import { structure } from "./sanity/structure";

export default defineConfig({
  basePath: "/studio",

  // 🔥 Hardcoded project connection
  projectId: "f4c8zi5a",
  dataset: "production",

  schema,

  plugins: [
    structureTool({ structure }),

    visionTool({
      defaultApiVersion: "2025-11-27",
    }),

    muxInput({
      defaultSigned: true,
      video_quality: "plus",
      defaultPublic: false,
      defaultAutogeneratedSubtitleLang: "en",
    }),
  ],
});
